spring.application.name=InvAgent

spring.datasource.url=jdbc:mysql://localhost:3306/supply_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

gemini.api.key=AIzaSyA-1-TvR4RTnq4TlM4FwfE8nPtH7xSx_jQ

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true